name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Deploy to Streamlit Cloud
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        streamlit run app.py
