name: Deploy notebook heart_disease_cla

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
          pip install -r requirements.txt
          pip install jupyter

    - name: Verify models
      run: |
       if [ ! -d "models" ]; then
          echo "Error: models directory not found."
          exit 1
       fi
       ls models/*.pkl || { echo "Error: No .pkl files found in models/"; exit 1; }
         
    # Step : Run notebook to train models
    - name: Train models from notebook
      run: |
          jupyter nbconvert --execute --to notebook --inplace notebooks/heart_disease_classification.ipynb
    
    #- name: Deploy to Streamlit Cloud
    #  run: |
    #    python3 -m venv venv
    #    source venv/bin/activate
    #    pip install -r requirements.txt
    #    streamlit run app.py
